import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";
import { LoadingBar } from "./components/LoadingBar";
// import { ModuleRegistry, AllCommunityModule } from "ag-grid-community";

// ModuleRegistry.registerModules([AllCommunityModule]);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const techStack = [
    "Nextjs",
    "React",
    "Redux Toolkit",
    "RTK-Query",
    "Ag-Grid",
    "TailwindCSS",
  ];

  return (
    <StoreProvider>
      <LoadingBar />
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
        >
          <div className="flex flex-col h-screen">
            <div className="flex-grow">{children}</div>
            <footer className="grid grid-cols-1 md:grid-cols-4 gap-4 flex-wrap items-start justify-center p-8 bg-violet-950">
              <div className="md:col-start-2 items-start">
                <h3 className="text-2xl mb-4 font-semibold">Powered by</h3>
                <ul className="p-2">
                  {techStack.map((t, i) => (
                    <li key={i} className="mb-2">
                      {t}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="md:col-start-3 item-start">
                <h3 className="text-2xl font-semibold">Contact Info</h3>
                <h3 className="text-xl my-2 ms-2 font-medium">
                  Allison Barros
                </h3>
                <ul className="p-2">
                  <li className="mb-2">
                    <a
                      href="https://www.linkedin.com/in/allison-barros/"
                      className="flex leading-7 gap-2 cursor-pointer"
                      target="_blank"
                    >
                      <svg
                        className="w-6 h-6 text-gray-800 dark:text-white"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        fill="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          fillRule="evenodd"
                          d="M12.51 8.796v1.697a3.738 3.738 0 0 1 3.288-1.684c3.455 0 4.202 2.16 4.202 4.97V19.5h-3.2v-5.072c0-1.21-.244-2.766-2.128-2.766-1.827 0-2.139 1.317-2.139 2.676V19.5h-3.19V8.796h3.168ZM7.2 6.106a1.61 1.61 0 0 1-.988 1.483 1.595 1.595 0 0 1-1.743-.348A1.607 1.607 0 0 1 5.6 4.5a1.601 1.601 0 0 1 1.6 1.606Z"
                          clipRule="evenodd"
                        />
                        <path d="M7.2 8.809H4V19.5h3.2V8.809Z" />
                      </svg>
                      <span className="hover:underline decoration-violet-500 decoration-2">
                        LinkedIn
                      </span>
                    </a>
                  </li>
                  <li className="mb-2">
                    <a
                      href="https://github.com/allisonbarrosx"
                      className="flex leading-7 gap-2 cursor-pointer"
                      target="_blank"
                    >
                      <svg
                        className="w-6 h-6 text-gray-800 dark:text-white"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        fill="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          fillRule="evenodd"
                          d="M12.006 2a9.847 9.847 0 0 0-6.484 2.44 10.32 10.32 0 0 0-3.393 6.17 10.48 10.48 0 0 0 1.317 6.955 10.045 10.045 0 0 0 5.4 4.418c.504.095.683-.223.683-.494 0-.245-.01-1.052-.014-1.908-2.78.62-3.366-1.21-3.366-1.21a2.711 2.711 0 0 0-1.11-1.5c-.907-.637.07-.621.07-.621.317.044.62.163.885.346.266.183.487.426.647.71.135.253.318.476.538.655a2.079 2.079 0 0 0 2.37.196c.045-.52.27-1.006.635-1.37-2.219-.259-4.554-1.138-4.554-5.07a4.022 4.022 0 0 1 1.031-2.75 3.77 3.77 0 0 1 .096-2.713s.839-.275 2.749 1.05a9.26 9.26 0 0 1 5.004 0c1.906-1.325 2.74-1.05 2.74-1.05.37.858.406 1.828.101 2.713a4.017 4.017 0 0 1 1.029 2.75c0 3.939-2.339 4.805-4.564 5.058a2.471 2.471 0 0 1 .679 1.897c0 1.372-.012 2.477-.012 2.814 0 .272.18.592.687.492a10.05 10.05 0 0 0 5.388-4.421 10.473 10.473 0 0 0 1.313-6.948 10.32 10.32 0 0 0-3.39-6.165A9.847 9.847 0 0 0 12.007 2Z"
                          clipRule="evenodd"
                        />
                      </svg>
                      <span className="hover:underline decoration-violet-500 decoration-2">
                        Github
                      </span>
                    </a>
                  </li>
                  <li className="mb-2">
                    <a
                      href="mailto:barros.allison@gmail.com"
                      className="flex leading-7 gap-2 cursor-pointer"
                      target="_blank"
                    >
                      <svg
                        className="w-6 h-6 text-gray-800 dark:text-white"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        fill="none"
                        viewBox="0 0 24 24"
                      >
                        <path
                          stroke="currentColor"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M11 16v-5.5A3.5 3.5 0 0 0 7.5 7m3.5 9H4v-5.5A3.5 3.5 0 0 1 7.5 7m3.5 9v4M7.5 7H14m0 0V4h2.5M14 7v3m-3.5 6H20v-6a3 3 0 0 0-3-3m-2 9v4m-8-6.5h1"
                        />
                      </svg>
                      <span className="hover:underline decoration-violet-500 decoration-2">
                        Email
                      </span>
                    </a>
                  </li>
                </ul>
              </div>
            </footer>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
